# Generated by Django 4.2.4 on 2024-04-22 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auxiliares', '0040_condicionestrabajoventilador_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SalidaEvaluacion',
            new_name='SalidaEvaluacionVentilador',
        ),
       migrations.AddField(
            model_name='evaluacionventilador',
            name='fecha',
            field=models.DateTimeField(auto_created=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluacionventilador',
            name='salida',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='auxiliares.salidaevaluacionventilador'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluacionventilador',
            name='ventilador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='auxiliares.ventilador'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluacionventilador',
            name='visible',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ventilador',
            name='creado_al',
            field=models.DateTimeField(auto_created=True),
        ),
        migrations.AlterModelTable(
            name='evaluacionventilador',
            table='ventiladores_evaluacion',
        ),
    ]
