# Generated by Django 4.2.4 on 2025-02-11 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0083_alter_evaluacionesintercambiador_ensuciamiento'),
        ('compresores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etapacompresor',
            name='velocidad_diseno',
        ),
        migrations.RemoveField(
            model_name='etapacompresor',
            name='velocidad_normal',
        ),
        migrations.RemoveField(
            model_name='ladoetapacompresor',
            name='n',
        ),
        migrations.AddField(
            model_name='composiciongases',
            name='compuesto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='intercambiadores.fluido'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='etapacompresor',
            name='cabezal_unidad',
            field=models.ForeignKey(blank=True, default=4, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unidad_cabezal_compresor', to='intercambiadores.unidades'),
        ),
        migrations.AddField(
            model_name='etapacompresor',
            name='curva_caracteristica',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='etapacompresor',
            name='densidad_unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unidad_densidad_compresor', to='intercambiadores.unidades'),
        ),
        migrations.AddField(
            model_name='etapacompresor',
            name='flujo_masico_unidad',
            field=models.ForeignKey(blank=True, default=54, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unidad_flujo_masico_compresor', to='intercambiadores.unidades'),
        ),
        migrations.AddField(
            model_name='etapacompresor',
            name='flujo_molar_unidad',
            field=models.ForeignKey(blank=True, default=94, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unidad_flujo_molar_compresor', to='intercambiadores.unidades'),
        ),
        migrations.AddField(
            model_name='etapacompresor',
            name='potencia_unidad',
            field=models.ForeignKey(blank=True, default=53, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unidad_potencia_etapa_compresor', to='intercambiadores.unidades'),
        ),
        migrations.AddField(
            model_name='etapacompresor',
            name='volumen_unidad',
            field=models.ForeignKey(blank=True, default=34, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unidad_volumen_etapa_compresor', to='intercambiadores.unidades'),
        ),
        migrations.AddField(
            model_name='ladoetapacompresor',
            name='presion_unidad',
            field=models.ForeignKey(blank=True, default=7, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unidad_presion_etapa_compresor', to='intercambiadores.unidades'),
        ),
        migrations.AddField(
            model_name='ladoetapacompresor',
            name='temp_unidad',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unidad_temp_etapa_compresor', to='intercambiadores.unidades'),
        ),
        migrations.AlterField(
            model_name='propiedadescompresor',
            name='unidad_potencia',
            field=models.ForeignKey(blank=True, default=53, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unidad_potencia_compresor', to='intercambiadores.unidades'),
        ),
        migrations.AlterField(
            model_name='propiedadescompresor',
            name='unidad_velocidad',
            field=models.ForeignKey(blank=True, default=52, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unidad_velocidad_compresor', to='intercambiadores.unidades'),
        ),
    ]
