# Generated by Django 4.2.4 on 2023-08-29 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fluido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Intercambiador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CondicionesDiseno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('temp_in_carcasa', models.DecimalField(decimal_places=4, max_digits=7, verbose_name='Temp. IN [°C] - Lado Carcasa')),
                ('temp_out_carcasa', models.DecimalField(decimal_places=4, max_digits=7, verbose_name='Temp. OUT [°C] - Lado Carcasa')),
                ('temp_in_tubo', models.DecimalField(decimal_places=4, max_digits=7, verbose_name='Temp. IN [°C] - Lado Tubo')),
                ('temp_out_tubo', models.DecimalField(decimal_places=4, max_digits=7, verbose_name='Temp. OUT [°C] - Lado tubo')),
                ('cp_carcasa', models.DecimalField(decimal_places=4, max_digits=6, null=True, verbose_name='cp [Kcal/Kg°C] - Lado Carcasa')),
                ('cp_tubo', models.DecimalField(decimal_places=4, max_digits=5, verbose_name='cp [Kcal/Kg°C] - Lado Tubo')),
                ('q', models.DecimalField(decimal_places=4, max_digits=11, verbose_name='Q [Kcal/h]')),
                ('lmtd', models.DecimalField(decimal_places=4, max_digits=7, verbose_name='LMTD')),
                ('ua', models.DecimalField(decimal_places=4, max_digits=11, verbose_name='UA [kcal/h.C]')),
                ('area', models.DecimalField(decimal_places=4, max_digits=7, verbose_name='Área m²')),
                ('u', models.DecimalField(decimal_places=4, max_digits=9, verbose_name='U [kcal/h.C.m²]')),
                ('ntu', models.DecimalField(decimal_places=4, max_digits=5, verbose_name='NTU')),
                ('efectividad', models.DecimalField(decimal_places=4, max_digits=5, verbose_name='Efectividad [ԑ]')),
                ('eficiencia', models.DecimalField(decimal_places=4, max_digits=8, verbose_name='Eficiencia [Ѱ] [%]')),
                ('flujo_agua', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Flujo de agua/unidad [Kg/h]')),
                ('flujo_proceso', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Flujo de proceso/unidad [Kg/h]')),
                ('numero_carcasas', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='No. carcasas/unidad')),
                ('area_carcasas', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Área/carcasa')),
                ('carcasas_calculadas', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Carcasas Calculadas')),
                ('pasos_carcasa', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='No. Pasos/Carcasa')),
                ('entradas_agua', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='No. Entradas de Agua/Unidad')),
                ('fluido_servicio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='intercambiadores.fluido', verbose_name='Fluido Lado Servicio')),
                ('intercambiador', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='intercambiadores.intercambiador')),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='intercambiadores.planta')),
            ],
        ),
    ]
