# Generated by Django 4.2.4 on 2023-08-29 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condicionesdiseno',
            name='intercambiador',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='intercambiadores.intercambiador'),
        ),
        migrations.AlterModelTable(
            name='area',
            table='area',
        ),
        migrations.AlterModelTable(
            name='condicionesdiseno',
            table='condiciones_diseno',
        ),
        migrations.AlterModelTable(
            name='fluido',
            table='fluido',
        ),
        migrations.AlterModelTable(
            name='intercambiador',
            table='intercambiador',
        ),
        migrations.AlterModelTable(
            name='planta',
            table='planta',
        ),
    ]
