# Generated by Django 4.2.4 on 2023-08-29 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0002_alter_condicionesdiseno_intercambiador_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametrosDiseno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('longitud_tubo', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Longitud del tubo (m)')),
                ('factor_ensuciamiento', models.DecimalField(decimal_places=7, max_digits=8, verbose_name='Factor de ensuciamiento [h.m2.ºC/Kcal] (Lado Tubo y Carcasa)')),
                ('diametro_in_carcasa', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Diámetro interno carcasa [mm]')),
                ('diametro_ex_carcasa', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Diámetro externo carcasa [mm]')),
                ('usucio', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Usucio  [kcal/h.C.m2] (condiciones de diseño)')),
                ('efectividad', models.DecimalField(decimal_places=5, max_digits=6, verbose_name='Efectividad [ԑ] (condiciones de diseño)')),
                ('ntu', models.DecimalField(decimal_places=5, max_digits=6, verbose_name='NTU (condiciones máximas)')),
                ('eficiencia', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Eficiencia [Ѱ] (condiciones máximas) [%]')),
                ('material_tubos', models.CharField(max_length=50)),
                ('conductividad', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Conductividad')),
                ('diametro_ex_tubos', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Diámetro externo tubos [mm]')),
                ('diametro_in_tubos', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Diámetro interno tubos [mm]')),
                ('numero_tubos', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Número de tubos')),
                ('arreglo_tubos', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Arreglo de los tubos [mm]')),
                ('pitch', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Pitch [mm]')),
                ('ensuciamiento_calculado', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Ensuciamiento Calculado')),
                ('intercambiador', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='intercambiadores.intercambiador')),
            ],
        ),
        migrations.CreateModel(
            name='CondicionesMaximas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('temp_in_carcasa', models.DecimalField(decimal_places=4, max_digits=7, verbose_name='Temp. IN [°C] - Lado Carcasa')),
                ('temp_out_carcasa', models.DecimalField(decimal_places=4, max_digits=7, verbose_name='Temp. OUT [°C] - Lado Carcasa')),
                ('temp_in_tubo', models.DecimalField(decimal_places=4, max_digits=7, verbose_name='Temp. IN [°C] - Lado Tubo')),
                ('temp_out_tubo', models.DecimalField(decimal_places=4, max_digits=7, verbose_name='Temp. OUT [°C] - Lado tubo')),
                ('cp_prom_carcasa', models.DecimalField(decimal_places=4, max_digits=6, null=True, verbose_name='cp prom. [Kcal/Kg°C] - Lado Carcasa')),
                ('cp_prom_tubo', models.DecimalField(decimal_places=4, max_digits=5, verbose_name='cp prom. [Kcal/Kg°C] - Lado Tubo')),
                ('q', models.DecimalField(decimal_places=4, max_digits=11, verbose_name='Q [Kcal/h]')),
                ('lmtd', models.DecimalField(decimal_places=4, max_digits=7, verbose_name='LMTD')),
                ('ua', models.DecimalField(decimal_places=4, max_digits=11, verbose_name='UA [kcal/h.C]')),
                ('area', models.DecimalField(decimal_places=4, max_digits=7, verbose_name='Área m²')),
                ('u', models.DecimalField(decimal_places=4, max_digits=9, verbose_name='U [kcal/h.C.m²]')),
                ('ntu', models.DecimalField(decimal_places=4, max_digits=5, verbose_name='NTU')),
                ('efectividad', models.DecimalField(decimal_places=4, max_digits=5, verbose_name='Efectividad [ԑ]')),
                ('eficiencia', models.DecimalField(decimal_places=4, max_digits=8, verbose_name='Eficiencia [Ѱ] [%]')),
                ('flujo_agua', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Flujo de agua/unidad [Kg/h]')),
                ('flujo_proceso', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Flujo de proceso/unidad [Kg/h]')),
                ('numero_carcasas', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='No. carcasas/unidad')),
                ('area_carcasas', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Área/carcasa')),
                ('carcasas_calculadas', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Carcasas Calculadas')),
                ('pasos_carcasa', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='No. Pasos/Carcasa')),
                ('entradas_agua', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='No. Entradas de Agua/Unidad')),
                ('fluido_servicio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='intercambiadores.fluido', verbose_name='Fluido Lado Servicio')),
                ('intercambiador', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='intercambiadores.intercambiador')),
            ],
            options={
                'db_table': 'condiciones_maximas',
            },
        ),
    ]
