# Generated by Django 4.2.4 on 2023-08-29 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0003_parametrosdiseno_condicionesmaximas'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrosdiseno',
            name='espesor_tubos',
            field=models.DecimalField(decimal_places=4, default=4.5, max_digits=8, verbose_name='Espesor de los Tubos [mm]'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parametrosdiseno',
            name='ensuciamiento_calculado',
            field=models.DecimalField(decimal_places=4, max_digits=8, null=True, verbose_name='Ensuciamiento Calculado'),
        ),
        migrations.AlterField(
            model_name='parametrosdiseno',
            name='material_tubos',
            field=models.CharField(max_length=50, verbose_name='Material de los Tubos'),
        ),
    ]
