# Generated by Django 4.2.4 on 2023-08-29 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0004_parametrosdiseno_espesor_tubos_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='parametrosdiseno',
            table='parametros_diseno',
        ),
    ]
