# Generated by Django 4.2.4 on 2023-08-31 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0005_alter_parametrosdiseno_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='intercambiador',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='intercambiadores.area'),
            preserve_default=False,
        ),
    ]
