# Generated by Django 4.2.4 on 2023-08-31 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0006_intercambiador_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condicionesdiseno',
            name='intercambiador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='intercambiadores.intercambiador'),
        ),
        migrations.AlterField(
            model_name='condicionesmaximas',
            name='intercambiador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='intercambiadores.intercambiador'),
        ),
        migrations.AlterField(
            model_name='parametrosdiseno',
            name='intercambiador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='intercambiadores.intercambiador'),
        ),
    ]
