# Generated by Django 4.2.4 on 2023-08-31 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0007_alter_condicionesdiseno_intercambiador_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condicionesdiseno',
            name='fluido_servicio',
        ),
        migrations.RemoveField(
            model_name='condicionesmaximas',
            name='fluido_servicio',
        ),
        migrations.AddField(
            model_name='intercambiador',
            name='fluido_interno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fluido_interno', to='intercambiadores.fluido', verbose_name='Fluido Lado Interno'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intercambiador',
            name='fluido_servicio',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fluido_servicio', to='intercambiadores.fluido', verbose_name='Fluido Lado Servicio'),
            preserve_default=False,
        ),
    ]
