# Generated by Django 4.2.4 on 2023-08-31 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0008_remove_condicionesdiseno_fluido_servicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intercambiador',
            name='codigo',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='fluido',
            name='codigo',
            field=models.CharField(default='CW', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fluido',
            name='nombre',
            field=models.CharField(max_length=25),
        ),
    ]
