# Generated by Django 4.2.4 on 2023-08-31 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0009_fluido_codigo_alter_fluido_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fluido',
            name='codigo',
            field=models.CharField(max_length=5),
        ),
        migrations.RemoveField(
            model_name='intercambiador',
            name='fluido_interno',
        ),
        migrations.RemoveField(
            model_name='intercambiador',
            name='fluido_servicio',
        ),
        migrations.AddField(
            model_name='intercambiador',
            name='fluido_interno',
            field=models.ManyToManyField(related_name='fluido_interno', to='intercambiadores.fluido', verbose_name='Fluido Lado Interno'),
        ),
        migrations.AddField(
            model_name='intercambiador',
            name='fluido_servicio',
            field=models.ManyToManyField(related_name='fluido_servicio', to='intercambiadores.fluido', verbose_name='Fluido Lado Servicio'),
        ),
    ]
