# Generated by Django 4.2.4 on 2023-08-31 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0011_remove_intercambiador_fluido_interno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrosdiseno',
            name='fluido_interno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fluido_interno_parametros', to='intercambiadores.fluido', verbose_name='Fluido Lado Interno'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parametrosdiseno',
            name='fluido_servicio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fluido_servicio_parametros', to='intercambiadores.fluido', verbose_name='Fluido Lado Servicio'),
            preserve_default=False,
        ),
    ]
