# Generated by Django 4.2.4 on 2023-08-31 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0012_parametrosdiseno_fluido_interno_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parametrosdiseno',
            name='efectividad',
        ),
        migrations.RemoveField(
            model_name='parametrosdiseno',
            name='eficiencia',
        ),
        migrations.RemoveField(
            model_name='parametrosdiseno',
            name='ntu',
        ),
        migrations.RemoveField(
            model_name='parametrosdiseno',
            name='usucio',
        ),
        migrations.AddField(
            model_name='parametrosdiseno',
            name='efectividad_diseno',
            field=models.DecimalField(decimal_places=5, max_digits=6, null=True, verbose_name='Efectividad [ԑ] (condiciones de diseño)'),
        ),
        migrations.AddField(
            model_name='parametrosdiseno',
            name='efectividad_maximas',
            field=models.DecimalField(decimal_places=5, max_digits=6, null=True, verbose_name='Efectividad [ԑ] (condiciones de diseño)'),
        ),
        migrations.AddField(
            model_name='parametrosdiseno',
            name='eficiencia_diseno',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Eficiencia [Ѱ] (condiciones máximas) [%]'),
        ),
        migrations.AddField(
            model_name='parametrosdiseno',
            name='eficiencia_maximas',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Eficiencia [Ѱ] (condiciones máximas) [%]'),
        ),
        migrations.AddField(
            model_name='parametrosdiseno',
            name='ntu_diseno',
            field=models.DecimalField(decimal_places=5, max_digits=6, null=True, verbose_name='NTU (condiciones máximas)'),
        ),
        migrations.AddField(
            model_name='parametrosdiseno',
            name='ntu_maximas',
            field=models.DecimalField(decimal_places=5, max_digits=6, null=True, verbose_name='NTU (condiciones máximas)'),
        ),
        migrations.AddField(
            model_name='parametrosdiseno',
            name='usucio_diseno',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Usucio  [kcal/h.C.m2] (condiciones de diseño)'),
        ),
        migrations.AddField(
            model_name='parametrosdiseno',
            name='usucio_maximas',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Usucio  [kcal/h.C.m2] (condiciones de diseño)'),
        ),
        migrations.AlterField(
            model_name='parametrosdiseno',
            name='diametro_ex_carcasa',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Diámetro externo carcasa [mm]'),
        ),
        migrations.AlterField(
            model_name='parametrosdiseno',
            name='diametro_ex_tubos',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Diámetro externo tubos [mm]'),
        ),
        migrations.AlterField(
            model_name='parametrosdiseno',
            name='diametro_in_carcasa',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Diámetro interno carcasa [mm]'),
        ),
        migrations.AlterField(
            model_name='parametrosdiseno',
            name='diametro_in_tubos',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Diámetro interno tubos [mm]'),
        ),
        migrations.AlterField(
            model_name='parametrosdiseno',
            name='espesor_tubos',
            field=models.DecimalField(decimal_places=4, max_digits=8, null=True, verbose_name='Espesor de los Tubos [mm]'),
        ),
        migrations.AlterField(
            model_name='parametrosdiseno',
            name='factor_ensuciamiento',
            field=models.DecimalField(decimal_places=7, max_digits=8, null=True, verbose_name='Factor de ensuciamiento [h.m2.ºC/Kcal] (Lado Tubo y Carcasa)'),
        ),
        migrations.AlterField(
            model_name='parametrosdiseno',
            name='longitud_tubo',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Longitud del tubo (m)'),
        ),
        migrations.AlterField(
            model_name='parametrosdiseno',
            name='material_tubos',
            field=models.CharField(max_length=50, null=True, verbose_name='Material de los Tubos'),
        ),
    ]
