# Generated by Django 4.2.4 on 2023-08-31 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0013_remove_parametrosdiseno_efectividad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulacionIntercambiador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('condiciones', models.CharField(choices=[('D', 'Diseño'), ('M', 'Máximas')], max_length=1)),
                ('fecha', models.DateTimeField(null=True, verbose_name='Fecha de la Simulación')),
                ('temp_in_serv', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Temperatura de Entrada (Servicio)')),
                ('temp_out_serv', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Temperatura de Salida (Servicio)')),
                ('temp_in_proceso', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Temperatura de Entrada (Proceso)')),
                ('temp_out_proceso', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Temperatura de Salida (Proceso)')),
                ('flujo_interno', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Flujo Másico Total Kg/h (Proceso)')),
                ('flujo_externo', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Flujo Másico Total Kg/h (Proceso)')),
                ('lmtd', models.DecimalField(decimal_places=4, max_digits=9, verbose_name='LMTD')),
                ('a_transferencia', models.DecimalField(decimal_places=4, max_digits=9, verbose_name='Área de Transferencia')),
                ('u', models.DecimalField(decimal_places=4, max_digits=9, verbose_name='U [Kcal/h.°C.m2]')),
                ('ua', models.DecimalField(decimal_places=4, max_digits=9, verbose_name='UA [Kcal/h.C]')),
                ('ntu', models.DecimalField(decimal_places=4, max_digits=9, verbose_name='NTU')),
                ('efectividad', models.DecimalField(decimal_places=4, max_digits=9, verbose_name='Efectividad')),
                ('eficiencia', models.DecimalField(decimal_places=4, max_digits=9, verbose_name='Eficiencia')),
                ('ensuciamiento', models.DecimalField(decimal_places=4, max_digits=9, verbose_name='Ensuciamiento')),
                ('intercambiador', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='intercambiadores.intercambiador')),
            ],
            options={
                'db_table': 'simulacion_intercambiador',
            },
        ),
    ]
