# Generated by Django 4.2.4 on 2023-08-31 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0014_simulacionintercambiador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulacionintercambiador',
            name='condiciones',
        ),
        migrations.AddField(
            model_name='simulacionintercambiador',
            name='condiciones_diseno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='intercambiadores.condicionesdiseno'),
        ),
        migrations.AddField(
            model_name='simulacionintercambiador',
            name='condiciones_maximas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='intercambiadores.condicionesmaximas'),
        ),
    ]
