# Generated by Django 4.2.4 on 2023-09-01 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0015_remove_simulacionintercambiador_condiciones_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CondicionesSimulacionTubos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('D', 'Diseño'), ('M', 'Máximas')], default='D', max_length=1)),
                ('temp_in_carcasa', models.DecimalField(decimal_places=4, max_digits=7, verbose_name='Temp. IN [°C] - Lado Carcasa')),
                ('temp_out_carcasa', models.DecimalField(decimal_places=4, max_digits=7, verbose_name='Temp. OUT [°C] - Lado Carcasa')),
                ('temp_in_tubo', models.DecimalField(decimal_places=4, max_digits=7, verbose_name='Temp. IN [°C] - Lado Tubo')),
                ('temp_out_tubo', models.DecimalField(decimal_places=4, max_digits=7, verbose_name='Temp. OUT [°C] - Lado tubo')),
                ('cp_carcasa', models.DecimalField(decimal_places=4, max_digits=6, null=True, verbose_name='cp [Kcal/Kg°C] - Lado Carcasa')),
                ('cp_tubo', models.DecimalField(decimal_places=4, max_digits=5, verbose_name='cp [Kcal/Kg°C] - Lado Tubo')),
                ('q', models.DecimalField(decimal_places=4, max_digits=11, verbose_name='Q [Kcal/h]')),
                ('lmtd', models.DecimalField(decimal_places=4, max_digits=7, verbose_name='LMTD')),
                ('ua', models.DecimalField(decimal_places=4, max_digits=11, verbose_name='UA [kcal/h.C]')),
                ('area', models.DecimalField(decimal_places=4, max_digits=7, verbose_name='Área m²')),
                ('u', models.DecimalField(decimal_places=4, max_digits=9, verbose_name='U [kcal/h.C.m²]')),
                ('ntu', models.DecimalField(decimal_places=4, max_digits=5, verbose_name='NTU')),
                ('efectividad', models.DecimalField(decimal_places=4, max_digits=5, verbose_name='Efectividad [ԑ]')),
                ('eficiencia', models.DecimalField(decimal_places=4, max_digits=8, verbose_name='Eficiencia [Ѱ] [%]')),
                ('flujo_agua', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Flujo de agua/unidad [Kg/h]')),
                ('flujo_proceso', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Flujo de proceso/unidad [Kg/h]')),
                ('numero_carcasas', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='No. carcasas/unidad')),
                ('area_carcasas', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Área/carcasa')),
                ('carcasas_calculadas', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Carcasas Calculadas')),
                ('pasos_carcasa', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='No. Pasos/Carcasa')),
                ('entradas_agua', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='No. Entradas de Agua/Unidad')),
                ('fluido_interno', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fluido_interno_diseno', to='intercambiadores.fluido', verbose_name='Fluido Lado Interno')),
                ('fluido_servicio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fluido_servicio_diseno', to='intercambiadores.fluido', verbose_name='Fluido Lado Servicio')),
            ],
            options={
                'db_table': 'condiciones_simulacion_tubos',
            },
        ),
        migrations.RemoveField(
            model_name='condicionesmaximas',
            name='fluido_interno',
        ),
        migrations.RemoveField(
            model_name='condicionesmaximas',
            name='fluido_servicio',
        ),
        migrations.RemoveField(
            model_name='condicionesmaximas',
            name='intercambiador',
        ),
        migrations.RemoveField(
            model_name='parametrosdiseno',
            name='arreglo_tubos',
        ),
        migrations.RemoveField(
            model_name='parametrosdiseno',
            name='conductividad',
        ),
        migrations.RemoveField(
            model_name='parametrosdiseno',
            name='diametro_ex_carcasa',
        ),
        migrations.RemoveField(
            model_name='parametrosdiseno',
            name='diametro_ex_tubos',
        ),
        migrations.RemoveField(
            model_name='parametrosdiseno',
            name='diametro_in_carcasa',
        ),
        migrations.RemoveField(
            model_name='parametrosdiseno',
            name='diametro_in_tubos',
        ),
        migrations.RemoveField(
            model_name='parametrosdiseno',
            name='ensuciamiento_calculado',
        ),
        migrations.RemoveField(
            model_name='parametrosdiseno',
            name='espesor_tubos',
        ),
        migrations.RemoveField(
            model_name='parametrosdiseno',
            name='factor_ensuciamiento',
        ),
        migrations.RemoveField(
            model_name='parametrosdiseno',
            name='longitud_tubo',
        ),
        migrations.RemoveField(
            model_name='parametrosdiseno',
            name='material_tubos',
        ),
        migrations.RemoveField(
            model_name='parametrosdiseno',
            name='numero_tubos',
        ),
        migrations.RemoveField(
            model_name='parametrosdiseno',
            name='pitch',
        ),
        migrations.RemoveField(
            model_name='simulacionintercambiador',
            name='condiciones_diseno',
        ),
        migrations.RemoveField(
            model_name='simulacionintercambiador',
            name='condiciones_maximas',
        ),
        migrations.AddField(
            model_name='intercambiador',
            name='arreglo_tubos',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Arreglo de los tubos [mm]'),
        ),
        migrations.AddField(
            model_name='intercambiador',
            name='conductividad',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Conductividad'),
        ),
        migrations.AddField(
            model_name='intercambiador',
            name='diametro_ex_carcasa',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Diámetro externo carcasa [mm]'),
        ),
        migrations.AddField(
            model_name='intercambiador',
            name='diametro_ex_tubos',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Diámetro externo tubos [mm]'),
        ),
        migrations.AddField(
            model_name='intercambiador',
            name='diametro_in_carcasa',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Diámetro interno carcasa [mm]'),
        ),
        migrations.AddField(
            model_name='intercambiador',
            name='diametro_in_tubos',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Diámetro interno tubos [mm]'),
        ),
        migrations.AddField(
            model_name='intercambiador',
            name='espesor_tubos',
            field=models.DecimalField(decimal_places=4, max_digits=8, null=True, verbose_name='Espesor de los Tubos [mm]'),
        ),
        migrations.AddField(
            model_name='intercambiador',
            name='factor_ensuciamiento',
            field=models.DecimalField(decimal_places=7, max_digits=8, null=True, verbose_name='Factor de ensuciamiento [h.m2.ºC/Kcal] (Lado Tubo y Carcasa)'),
        ),
        migrations.AddField(
            model_name='intercambiador',
            name='longitud_tubo',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Longitud del tubo (m)'),
        ),
        migrations.AddField(
            model_name='intercambiador',
            name='material_tubos',
            field=models.CharField(max_length=50, null=True, verbose_name='Material de los Tubos'),
        ),
        migrations.AddField(
            model_name='intercambiador',
            name='numero_tubos',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Número de tubos'),
        ),
        migrations.AddField(
            model_name='intercambiador',
            name='pitch',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Pitch [mm]'),
        ),
        migrations.AlterField(
            model_name='simulacionintercambiador',
            name='flujo_externo',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Flujo Másico Total Kg/h (Externo)'),
        ),
        migrations.AlterField(
            model_name='simulacionintercambiador',
            name='temp_in_proceso',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Temperatura de Entrada °C (Proceso)'),
        ),
        migrations.AlterField(
            model_name='simulacionintercambiador',
            name='temp_in_serv',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Temperatura de Entrada °C (Servicio)'),
        ),
        migrations.AlterField(
            model_name='simulacionintercambiador',
            name='temp_out_proceso',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Temperatura de Salida °C (Proceso)'),
        ),
        migrations.AlterField(
            model_name='simulacionintercambiador',
            name='temp_out_serv',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Temperatura de Salida °C (Servicio)'),
        ),
        migrations.DeleteModel(
            name='CondicionesDiseno',
        ),
        migrations.DeleteModel(
            name='CondicionesMaximas',
        ),
        migrations.AddField(
            model_name='condicionessimulaciontubos',
            name='intercambiador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='intercambiadores.intercambiador'),
        ),
        migrations.AddField(
            model_name='simulacionintercambiador',
            name='condiciones',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='intercambiadores.condicionessimulaciontubos'),
        ),
    ]
