# Generated by Django 4.2.4 on 2023-09-04 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0016_condicionessimulaciontubos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='condicionessimulaciontubos',
            name='intercambiador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='condiciones', to='intercambiadores.intercambiador'),
        ),
        migrations.CreateModel(
            name='Complejo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='intercambiadores.empresa')),
            ],
        ),
        migrations.AddField(
            model_name='planta',
            name='complejo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='intercambiadores.complejo'),
            preserve_default=False,
        ),
    ]
