# Generated by Django 4.2.4 on 2023-09-04 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0017_empresa_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='complejo',
            table='complejo',
        ),
        migrations.AlterModelTable(
            name='empresa',
            table='empresa',
        ),
    ]
